# -*- coding: utf-8 -*-
"""KMeans_clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19gpC5T6EADJFttGpkJiWjGwvMuKPSGny
"""

import numpy as np
import pandas as pd

data_frame = pd.read_csv('student_clustering.csv')
print(f"Data shape is: {data_frame.shape}")
print(f"The top rows are : \n{data_frame.head()}")

import matplotlib.pyplot as plt
plt.scatter(data_frame['cgpa'], data_frame['iq'])

from sklearn.cluster import KMeans

wcss = []

for i in range(1, 11):
  # Find KMeans for each cluster value
  km = KMeans(n_clusters=i)
  km.fit_predict(data_frame)

  # For each cluster add the wcss value
  wcss.append(km.inertia_)

print(wcss)

# Plotting the elbow curve
plt.plot(range(1, 11), wcss)

X = data_frame.iloc[:,:].values

model = KMeans(n_clusters=4)
y_means = model.fit_predict(X)

print(y_means)

plt.scatter(X[y_means == 0, 0], X[y_means == 0, 1], color = 'blue')
plt.scatter(X[y_means == 1, 0], X[y_means == 1, 1], color = 'red')
plt.scatter(X[y_means == 2, 0], X[y_means == 2, 1], color = 'green')
plt.scatter(X[y_means == 3, 0], X[y_means == 3, 1], color = 'violet')