# -*- coding: utf-8 -*-
"""Day_1_Perceptron.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W66w9aBKtFAtfGi8vA287FagCC0B_Fvm
"""

import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt

# Read the csv file
df = pd.read_csv("placement.csv")
# print the data frame
print(df)

# Check the dimensions of the data frame
print(df.shape)

# Print the top 5 data from the dataset
print(df.head())

# print(df["cgpa"][0], df["resume_score"][0])

sb.scatterplot(x=df["cgpa"], y=df["resume_score"], hue=df["placed"])

# For the x-axis, we take the first 2 coloumns
x = df.iloc[:, 0:2]

# For the y-axis, we take the last coloumn
y = df.iloc[:, -1]

# From sklearn models, we import the Perceptron model
from sklearn.linear_model import Perceptron
p = Perceptron()

#Training the perceptron
p.fit(x.values, y.values)

# Getting the values of weights of the attributes
p.coef_

#Getting the value of the bias of the attributes
p.intercept_

# Now, let's see the line plotted
from mlxtend.plotting import plot_decision_regions

plot_decision_regions(x.values, y.values, clf=p, legend=2)