# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nxdvc5LkHFyu80-e7EwnF5zKTOPkK4Mh
"""

class custom_linear_regression:

  def __init__(self):
    self.m = None
    self.b = None

  def fit(self, X_train, Y_train):

    num = 0
    den = 0

    for i in range(X_train.shape[0]):

      num = num + ((X_train[i] - X_train.mean())*(Y_train[i] - Y_train.mean()))
      den = den + ((X_train[i] - X_train.mean())*(X_train[i] - X_train.mean()))

    self.m = num/den
    self.b = Y_train.mean() - (self.m * X_train.mean())

    print(self.m)
    print(self.b)


  def predict(self, X_test):

    return (self.m * X_test) + self.b

import numpy as np
import pandas as pd

data_frame = pd.read_csv("placement.csv")
print(data_frame.head())

X = data_frame.iloc[:, 0].values
print(X)

Y = data_frame.iloc[:, 1].values
print(Y)

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

X_train.shape

linear_regression = custom_linear_regression()

linear_regression.fit(X_train, Y_train)

linear_regression.predict(X_test[0])