# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zh9XQiH3QgenAuucTi1DsXXKfaZKjAcI
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

data_frame = pd.read_csv("placement.csv")
print(data_frame.head())

print(data_frame['cgpa'].head())

plt.scatter(data_frame['cgpa'], data_frame['package'])
plt.xlabel('CGPA')
plt.ylabel('Package in LPA')

X = data_frame.iloc[:,0:1]
print(X)

Y = data_frame.iloc[:,-1]
print(Y)

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

from sklearn.linear_model import LinearRegression
linear_regression = LinearRegression()

linear_regression.fit(X_train, Y_train)

print(X_test.iloc[:10], end="\n*************\n")
print(Y_test.iloc[:10])

# linear_regression.predict()
print(X_test.iloc[0].values.reshape(1, 1))

print(linear_regression.predict(X_test))

plt.scatter(X_train, Y_train)
plt.plot(X_train, linear_regression.predict(X_train), color="violet")

theta_slope = linear_regression.coef_
print(f"The slope of the best-fit line is {theta_slope}")

intercept = linear_regression.intercept_
print(f"The intercept of the best-fit line is {intercept}")

# Let's calculate for the cgpa 8.58

# By linear_regression ::
print(linear_regression.predict(X_test.iloc[0].values.reshape(1, 1)))

# By best-fit line ::
print((theta_slope * X_test.iloc[0]) + intercept)